- name: determine if device is exist
  shell: blkid -s TYPE /dev/{{ disk_name }}1                                                                                                                                                                                                                                
  register: filesystem
  when: ansible_devices.{{ disk_name }} is defined
  ignore_errors: True

- name: Create a new primary partition if the partion is not exist or is not filesystem
  parted: device=/dev/{{ disk_name }} number=1 state=present
  when: ansible_devices.{{ disk_name }} is defined and filesystem.stdout.find('TYPE') != 1

- name: make filesystem for /dev/{{ disk_name }}1
  filesystem: dev=/dev/{{ disk_name }}1 fstype=ext4

- name: Add mount point to fstab
  mount: src=/dev/{{ disk_name }}1 path=/data fstype=ext4 state=mounted